version: "3.3"

services:
  db:
    container_name: wildcodeschool-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports: 
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: agence-expert-phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
      UPLOAD_LIMIT: 1G
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
